services:
  django:
    env_file:
      - .env
    build:
      context: .
    expose:
      - "8000"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - django
