services:
  django:
    env_file:
      - .env
    build:
      context: .
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - song-data:/app/media:r
    depends_on:
      - db
  
  db:
    build:
      context: ./database
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"

  spotify:
    env_file:
      - .env
    build:
      context: ./scripts
      dockerfile: ./Dockerfile
    volumes:
      - song-data:/app/data:rw
    command: python get_spotify.py --filter arsch

volumes:
  song-data:
  pgdata:

    
