services:
  django:
    env_file:
      - .env
    build:
      context: .
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - song-data:/app/media:r
    networks:
      - jonochen.net

  spotify:
    env_file:
      - .env
    build:
      context: ./scripts
      dockerfile: ./Dockerfile
    volumes:
      - song-data:/app/data:rw
    networks:
      - jonochen.net
    profiles: [spotify]
    command: python get_spotify.py --filter "arsch,aa"

  reset-daily:
    env_file:
      - .env
    build:
      context: ./scripts
      dockerfile: ./Dockerfile
    networks:
      - jonochen.net
    command: python reset_daily.py

volumes:
  song-data:

networks:
  jonochen.net:
    external: true

    
