services:
  django:
    env_file:
      - .env
    build:
      context: .
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
  
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"

  spotify:
    env_file:
      - .env
    build:
      context: ./scripts
      dockerfile: ./scripts/Dockerfile
    command: bash -c "sleep 10 && python scripts/get_spotify.py --filter arsch"

    
